-- SELECT COUNT(*) FROM actors
-- INSERT INTO actors(first_name,last_name,birthdate,number_oscars) VALUES ('Demi','Moore','','')
-- > syntax error because it's impossible to set '' to the field with type smallint or date, 
-- if '' in the field with type varchar - will be just empty space